name: EGU22 
channels:
  - conda-forge
dependencies:
  # the basics
  - python
  - rasterio
  - matplotlib
  - pandas
  - seaborn
  - jupyterlab
  - jupyterlab-spellchecker
  - voila
  - rise
  - ipywidgets
  - nodejs<17
